---
title: "plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plot

Make interactive plots in plotly. We will make examples using NYC airbnb datasets.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), ##drop_na(rating)
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)

```

Using plotly to make some quick plots.

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, alpha = 0.5, text = ~text_label) #text = ~text_label, alpha = 0.5
```

Next -- box plot.

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood, type = "box", colors = "viridis")
```

Do a bar chart with number of rentals.

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

```{r}
plot_ly (
type = 'choropleth' ,
locations = 
c( 'AZ', 'CA', 'VT' ) ,
locationmode = 'USA-states' ,
colorscale = 'Viridis' , z = c( 10, 20, 40 )) %>%
layout ( geo = list ( scope = 'usa' ))
```








